/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UiIndexImport } from './routes/ui/index'
import { Route as UiComponentNameImport } from './routes/ui/component.$name'

// Create/Update Routes

const UiIndexRoute = UiIndexImport.update({
  id: '/ui/',
  path: '/ui/',
  getParentRoute: () => rootRoute,
} as any)

const UiComponentNameRoute = UiComponentNameImport.update({
  id: '/ui/component/$name',
  path: '/ui/component/$name',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui/': {
      id: '/ui/'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiIndexImport
      parentRoute: typeof rootRoute
    }
    '/ui/component/$name': {
      id: '/ui/component/$name'
      path: '/ui/component/$name'
      fullPath: '/ui/component/$name'
      preLoaderRoute: typeof UiComponentNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/ui': typeof UiIndexRoute
  '/ui/component/$name': typeof UiComponentNameRoute
}

export interface FileRoutesByTo {
  '/ui': typeof UiIndexRoute
  '/ui/component/$name': typeof UiComponentNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/ui/': typeof UiIndexRoute
  '/ui/component/$name': typeof UiComponentNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/ui' | '/ui/component/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/ui' | '/ui/component/$name'
  id: '__root__' | '/ui/' | '/ui/component/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  UiIndexRoute: typeof UiIndexRoute
  UiComponentNameRoute: typeof UiComponentNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  UiIndexRoute: UiIndexRoute,
  UiComponentNameRoute: UiComponentNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/ui/",
        "/ui/component/$name"
      ]
    },
    "/ui/": {
      "filePath": "ui/index.tsx"
    },
    "/ui/component/$name": {
      "filePath": "ui/component.$name.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
