/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UiIndexImport } from './routes/ui/index'
import { Route as UiAboutImport } from './routes/ui/about'

// Create/Update Routes

const UiIndexRoute = UiIndexImport.update({
  id: '/ui/',
  path: '/ui/',
  getParentRoute: () => rootRoute,
} as any)

const UiAboutRoute = UiAboutImport.update({
  id: '/ui/about',
  path: '/ui/about',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui/about': {
      id: '/ui/about'
      path: '/ui/about'
      fullPath: '/ui/about'
      preLoaderRoute: typeof UiAboutImport
      parentRoute: typeof rootRoute
    }
    '/ui/': {
      id: '/ui/'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/ui/about': typeof UiAboutRoute
  '/ui': typeof UiIndexRoute
}

export interface FileRoutesByTo {
  '/ui/about': typeof UiAboutRoute
  '/ui': typeof UiIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/ui/about': typeof UiAboutRoute
  '/ui/': typeof UiIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/ui/about' | '/ui'
  fileRoutesByTo: FileRoutesByTo
  to: '/ui/about' | '/ui'
  id: '__root__' | '/ui/about' | '/ui/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  UiAboutRoute: typeof UiAboutRoute
  UiIndexRoute: typeof UiIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  UiAboutRoute: UiAboutRoute,
  UiIndexRoute: UiIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/ui/about",
        "/ui/"
      ]
    },
    "/ui/about": {
      "filePath": "ui/about.tsx"
    },
    "/ui/": {
      "filePath": "ui/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
